### ISSUE TITLE
Fix inconsistency with how API responses are being sent

### ISSUE THREAD

**Issue by Yvad60** [atlp-rwanda/phantom-be-codebandits#25]
There is inconsistency with how responses are now being sent from the backend especially when we are sending just short  messages to the user 
the `handleResponse` function that we are using to format our responses returns a response that includes `status`, `code`, and `data`, and this data field that actually contains information from the backend should be an object itself and it is in most cases but there are some cases the message is being sent just as a string especially when we are returning just a short message like `user deleted`, `operator updated`...

these changes should be made

```diff
{
status: "success",
code: "200",
- data: "driver updated successfully"
+ data: {message: "driver updated successfully"}
}
```
making our API responses consistent will prevent unnecessary checks that can be made during integration when someone doesn't know the exact data structure of the message coming from the backend

**Comment by feyton** [comment]
### Details
Hello @Yvad60 
Thank you for mentioning the issue, are you able to open a pull request that fix the issue? If so you may go ahead and let us know when its ready.
I would suggest starting from something like this

```
export const responseHandler = (res, code, message) => {
  let status;
  code > 400 ? (status = "success") : (status = "fail");
  let response = { status, code: code };
  if (typeof message == "string") {
    response["message"] = message;
  } else {
    response["data"] = message;
  }
  return res.status(code).json(response);
};

export default responseHandler;
```
